---
actuators:
  heater: "evok/relay/5/set"
  switch: "evok/relay/1/set"
sensors:
  heaterIn: 
    address: "heater/temperature/in"
  heaterOut:
    address: "heater/temperature/out"
  roomTemp:
    address: "climate/temperature/inside"
  tankUp:
    address: "tank/temperature/up"
settings:
  heaterCritical:
    address: "heater/settings/critical"
    value: 80
  hysteresis:
    address: "heater/settings/hysteresis"
    value: 1
  expected:
    address: "heater/settings/expected"
    value: 18
  tankMin:
    address: "heater/settings/tankmin"
    value: 45
  tankMax:
    address: "heater/settings/tankmax"
    value: 55